Added missing AlertConfig provider
The exception if there is no AlertConfig provider:

```
error_handler.js:50 EXCEPTION: Error in ./AppComponent class AppComponent - inline template:4:0 caused by: No provider for AlertConfig!ErrorHandler.handleError @ error_handler.js:50(anonymous function) @ application_ref.js:259ZoneDelegate.invoke @ zone.js:242onInvoke @ ng_zone.js:269ZoneDelegate.invoke @ zone.js:241Zone.run @ zone.js:113(anonymous function) @ zone.js:520ZoneDelegate.invokeTask @ zone.js:275onInvokeTask @ ng_zone.js:260ZoneDelegate.invokeTask @ zone.js:274Zone.runTask @ zone.js:151drainMicroTaskQueue @ zone.js:418
error_handler.js:52 ORIGINAL EXCEPTION: No provider for AlertConfig!ErrorHandler.handleError @ error_handler.js:52(anonymous function) @ application_ref.js:259ZoneDelegate.invoke @ zone.js:242onInvoke @ ng_zone.js:269ZoneDelegate.invoke @ zone.js:241Zone.run @ zone.js:113(anonymous function) @ zone.js:520ZoneDelegate.invokeTask @ zone.js:275onInvokeTask @ ng_zone.js:260ZoneDelegate.invokeTask @ zone.js:274Zone.runTask @ zone.js:151drainMicroTaskQueue @ zone.js:418
error_handler.js:55 ORIGINAL STACKTRACE:ErrorHandler.handleError @ error_handler.js:55(anonymous function) @ application_ref.js:259ZoneDelegate.invoke @ zone.js:242onInvoke @ ng_zone.js:269ZoneDelegate.invoke @ zone.js:241Zone.run @ zone.js:113(anonymous function) @ zone.js:520ZoneDelegate.invokeTask @ zone.js:275onInvokeTask @ ng_zone.js:260ZoneDelegate.invokeTask @ zone.js:274Zone.runTask @ zone.js:151drainMicroTaskQueue @ zone.js:418
error_handler.js:56 Error: DI Error
    at NoProviderError.BaseError [as constructor] (errors.js:31) [angular]
    at NoProviderError.AbstractProviderError [as constructor] (reflective_errors.js:53) [angular]
    at new NoProviderError (reflective_errors.js:102) [angular]
```